# Generated by Django 4.1.3 on 2023-03-13 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Token',
        ),
    ]
